on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: test_R

jobs:
  lint-project:
    runs-on: [ubuntu_latest]
    container: docker://dvcorg/cml:latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Setup Dependencies 
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
      - name: Analyse
        env:
           repo_token :: ${{secrets.GITHUB_TOKEN }}
        run: |
          R -e 'renv::run("ClassifyData.R")'
      
      
