on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: lint-project

jobs:
  lint-project:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: R-actions
        # You may pin to the exact commit or the version.
        # uses: Swechhya/R-actions@772117ee961f81f5e2b00c2406e84456dd62f7a4
        uses: Swechhya/R-actions@v1.2
        with:
          # What should be run? One of: ["all", "build"]
          action: all # optional, default is all
          # Is Bioconductor package needed? One of [true, false]
          needsBioc: false# optional
